use heng core
ThinkSpiritLab/Heng-Client pull request #9
Opened 2021-11-16 13:41 UTC by flaryer

use heng core

2021-11-16 13:42 UTC, flaryer commented
pending enough test

2021-11-16 16:39 UTC, A0nameless0man requested changes

2021-11-16 16:39 UTC, A0nameless0man commented on prepare-docker.sh
> +&& cd ~/Heng-Core && make && cp ~/Heng-Core/hc /usr/bin/hc && cd ~
后面也要rm这个文件夹

2021-11-16 16:43 UTC, flaryer commented on prepare-docker.sh
> +&& cd ~/Heng-Core && make && cp ~/Heng-Core/hc /usr/bin/hc && cd ~
是的

2021-11-18 15:22 UTC, A0nameless0man approved these changes

2021-11-19 06:06 UTC, merged